### ISSUE TITLE
插件无法正常工作

### ISSUE THREAD

**Issue by finddream2023** [snchengqi/course-robot#3]
按照教程安装之后（已设置允许弹窗），点击“开始学习”打开了专题之后，一直就没反应了，重试了几遍也是这样。
测试专题链接：https://kc.zhixueyun.com/#/study/subject/detail/d315420f-9750-4ca9-b48b-93acee4417f0
浏览器：Chrome 89.0.4389.90（正式版本） （32 位）

**Comment by snchengqi** [comment]
我这边可以学习你提供的专题，没法复现问题

**Comment by finddream2023** [comment]
> 我这边可以学习你提供的专题，没法复现问题

我用Edge浏览器下载插件就使用正常，如果用Chrome浏览器Chrome 89.0.4389.90（正式版本） （32 位）就不行，由于某些原因，又不能随便升级Chrome浏览器，只能暂时先用Edge来用着先了
![chrome](https://github.com/snchengqi/course-robot/assets/147569722/648d63ca-e440-417c-a023-8730a998e174)

**Comment by snchengqi** [comment]
按照相关文档Chrome88及以上是支持Chome Manifest V3的，你可以把报错日志发我看一下

**Comment by finddream2023** [comment]
报错日志可以在哪里看呢？

**Comment by snchengqi** [comment]
![1697523029530](https://github.com/snchengqi/course-robot/assets/30997359/98e9fb3f-61bd-4c2e-b205-7c5d8024ace0)
![1697523055666](https://github.com/snchengqi/course-robot/assets/30997359/f5748fdd-7c69-402a-86a0-cc580f2a2fbe)
根据图片查看service worker控制台

**Comment by finddream2023** [comment]
一点开视图就有黄色的消息：
DevTools failed to load SourceMap: Could not load content for chrome-extension://hcimhmjokhginbcihndlfgkiahgcfhpf/background.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
点击开始学习就有红色的报错：
Unchecked runtime.lastError: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
![devtools](https://github.com/snchengqi/course-robot/assets/147569722/f4241fa0-a084-45e6-9ba4-c3e782400158)

**Comment by snchengqi** [comment]
看报错的意思是需要配置访问相应域名的权限，我在manifest.json已经配置了，不知道为啥还有这个提示，目前猜测是Chrome浏览器版本原因
