### ISSUE TITLE
增加学习时间段功能

### ISSUE THREAD

**Issue by finddream2023** [snchengqi/course-robot#4]
课程一般都要比较长时间完成，开了插件之后，有时大半夜还在学习，这明显是不符合常理的。能不能增加一个功能，可以设置学习时间段（或者设置到了什么时候自动结束学习）？

**Comment by snchengqi** [comment]
可以手动点击结束学习按钮退出学习，暂不考虑支持该功能，后续可能新增到期自动结束学习
