### ISSUE TITLE
开始学习按钮可以只检测zhixueyun.com后缀吗，我们公司前缀不同，导致无法开始按钮

### ISSUE THREAD

**Issue by LastNever** [snchengqi/course-robot#5]
开始学习按钮可以只检测zhixueyun.com后缀吗，我们公司前缀不同，导致无法开始按钮

**Comment by snchengqi** [comment]
你们是什么公司？页面是否与电信的一致，如果不一致插件也不会生效，这样修改校验规则也没用

**Comment by LastNever** [comment]
> 你们是什么公司？页面是否与电信的一致，如果不一致插件也不会生效，这样修改校验规则也没用

页面基本一致的
![image](https://github.com/snchengqi/course-robot/assets/59238906/aaa3c33a-ff57-4c25-a3d3-206f3bb9d874)
![image](https://github.com/snchengqi/course-robot/assets/59238906/ce3b7ca3-4949-4dfd-9e2e-be47ac12073a)

**Comment by snchengqi** [comment]
把你们入口地址发我看一下

**Comment by LastNever** [comment]
> 把你们入口地址发我看一下

https://zghz.zhixueyun.com/

**Comment by snchengqi** [comment]
> > 把你们入口地址发我看一下
> 
> https://zghz.zhixueyun.com/

可以把你账号密码发我邮箱调试一下吗？snchengqi@163.com

**Comment by snchengqi** [comment]
已修改url校验规则，由于没有账号测试不保证功能正常运行。扩展程序在微软应用商店审核更新后，会提交源代码和安装包到github
